plugins {
    id("com.android.application")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
    // 💡 FIXED: Removed 'version' (handled by project-level file) and 'apply false' so it actually runs!
    id("com.google.gms.google-services")
}

android {
    namespace = "com.teamparadox.eduportal"
    
    // 💡 1. Override the compileSdk to 36 to satisfy dependency requirements
    compileSdk = 36
    ndkVersion = flutter.ndkVersion

    compileOptions {
        // Enable Core Library Desugaring for Java 8+ compatibility bridges
        isCoreLibraryDesugaringEnabled = true

        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.teamparadox.eduportal"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        
        // 💡 2. Override the targetSdk to 36 to match the compileSdk target
        targetSdk = 36
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    // 💡 ADDED: Custom Signing Configuration for GitHub Actions
    signingConfigs {
        create("release") {
            val keystoreFile = file("upload-keystore.jks")
            
            // If the keystore file exists (e.g., generated by GitHub Actions), use it securely
            if (keystoreFile.exists()) {
                storeFile = keystoreFile
                storePassword = System.getenv("KEY_STORE_PASSWORD")
                keyAlias = System.getenv("KEY_ALIAS")
                keyPassword = System.getenv("KEY_PASSWORD")
            } else {
                // Fallback to debug keystore so local testing on your laptop doesn't break
                val debugKeystore = file(System.getProperty("user.home") + "/.android/debug.keystore")
                if (debugKeystore.exists()) {
                    storeFile = debugKeystore
                    storePassword = "android"
                    keyAlias = "androiddebugkey"
                    keyPassword = "android"
                }
            }
        }
    }

    buildTypes {
        release {
            // 💡 FIXED: Now explicitly pointing to our newly created "release" signing configuration
            signingConfig = signingConfigs.getByName("release") 
            isMinifyEnabled = false
            isShrinkResources = false
            
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    
    dexOptions {
        javaMaxHeapSize = "1g"
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
    }
}

flutter {
    source = "../.."
}

dependencies {
    implementation(platform("com.google.firebase:firebase-bom:34.14.1"))
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")
    implementation("com.google.firebase:firebase-analytics")
    // 💡 ADDED: Required specifically for background push notifications
    implementation("com.google.firebase:firebase-messaging")
}